// vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import GraphqlRoute from './views/GraphqlRoute.vue';
import RestRoute from './views/RestRoute.vue';
import { stripAppBasePath, toAppHref } from './lib/routing';

type ModeId = 'server-rendered' | 'client-rendered';
type TransportId = 'rest' | 'graphql';

type BrowserLocationState = {
  pathname: string;
  search: string;
};

const NAV_ITEMS: Array<{
  mode: ModeId;
  transport: TransportId;
  title: string;
  href: string;
}> = [
  {
    mode: 'server-rendered',
    transport: 'rest',
    title: 'REST',
    href: '/server-rendered/rest?example=single-page&scenario=html-default-theme',
  },
  {
    mode: 'server-rendered',
    transport: 'graphql',
    title: 'GraphQL',
    href: '/server-rendered/graphql?example=single-page&demo=html-payload&scenario=html-default-theme',
  },
  {
    mode: 'client-rendered',
    transport: 'rest',
    title: 'REST',
    href: '/client-rendered/rest?example=single-page&scenario=component-rest-form',
  },
  {
    mode: 'client-rendered',
    transport: 'graphql',
    title: 'GraphQL',
    href: '/client-rendered/graphql?example=single-page&demo=component-payload',
  },
];

function readBrowserLocation(): BrowserLocationState {
  if (typeof window === 'undefined') {
    return {
      pathname: '/server-rendered/rest',
      search: '',
    };
  }
  return {
    pathname: stripAppBasePath(window.location.pathname || '/server-rendered/rest'),
    search: window.location.search,
  };
}

function normalizeLocation(pathname: string): { mode: ModeId; transport: TransportId } | null {
  const normalizedPathname = pathname === '/' ? '/server-rendered/rest' : pathname;
  const segments = normalizedPathname.split('/').filter(Boolean);
  if (segments.length < 2) {
    return null;
  }
  const [mode, transport] = segments;
  if ((mode === 'server-rendered' || mode === 'client-rendered') && (transport === 'rest' || transport === 'graphql')) {
    return {
      mode,
      transport,
    };
  }
  return null;
}

const location = ref<BrowserLocationState>(readBrowserLocation());

const activeLocation = computed(() => {
  return normalizeLocation(location.value.pathname) || {
    mode: 'server-rendered' as const,
    transport: 'rest' as const,
  };
});

function navigate(url: string, options?: { replace?: boolean }) {
  const method = options?.replace ? 'replaceState' : 'pushState';
  window.history[method]({}, '', toAppHref(url));
  location.value = readBrowserLocation();
}

function onPopState() {
  location.value = readBrowserLocation();
}

watch(
  () => [location.value.pathname, location.value.search] as const,
  () => {
    if (normalizeLocation(location.value.pathname)) {
      return;
    }
    navigate(`/server-rendered/rest${location.value.search}`, { replace: true });
  },
  {
    immediate: true,
  },
);

onMounted(() => {
  window.addEventListener('popstate', onPopState);
});

onUnmounted(() => {
  window.removeEventListener('popstate', onPopState);
});
</script>

<template>
  <header class="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur">
    <div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-3 shadow-[0_8px_24px_-18px_rgba(15,23,42,0.35)] md:px-8">
      <a
        :href="toAppHref('/server-rendered/rest?example=single-page&scenario=html-default-theme')"
        class="flex items-center gap-3"
        @click.prevent="navigate('/server-rendered/rest?example=single-page&scenario=html-default-theme')"
      >
        <div class="size-6 shrink-0">
          <svg viewBox="0 0 544.2 544.2" aria-hidden="true" class="size-full">
            <path d="M272.1 0C2.1 0 0 121.8 0 272.1s2.1 272.1 272.1 272.1 272.1-121.8 272.1-272.1S542.1 0 272.1 0z" fill="#ea3b3b" />
            <path d="M382.2 122.6H162.1c-13.8 0-25 11.2-25 25v249c0 13.8 11.2 25 25 25h220.1c13.8 0 25-11.2 25-25v-249c0-13.7-11.3-25-25-25zM272.1 363.3h-73.4c-10.1 0-18.3-8.2-18.3-18.3 0-10.1 8.2-18.3 18.3-18.3h73.4c10.1 0 18.3 8.2 18.3 18.3.1 10.1-8.2 18.3-18.3 18.3zm73.4-73.4H198.7c-10.1 0-18.3-8.2-18.3-18.3 0-10.1 8.2-18.3 18.3-18.3h146.8c10.1 0 18.3 8.2 18.3 18.3 0 10.1-8.2 18.3-18.3 18.3zm0-73.4H198.7c-10.1 0-18.3-8.2-18.3-18.3 0-10.1 8.2-18.3 18.3-18.3h146.8c10.1 0 18.3 8.2 18.3 18.3 0 10.1-8.2 18.3-18.3 18.3z" fill="#fff" />
          </svg>
        </div>
        <div>
          <p class="text-lg font-semibold text-slate-900">
            Formie Vue Starter
          </p>
        </div>
      </a>
    </div>
  </header>

  <main class="mx-auto grid max-w-7xl gap-8 p-6 md:grid-cols-[14rem_minmax(0,1fr)] md:p-8">
    <aside class="md:sticky md:top-24 md:self-start">
      <nav class="space-y-6">
        <div v-for="sectionMode in (['server-rendered', 'client-rendered'] as const)" :key="sectionMode" class="space-y-2">
          <p class="px-3 text-sm font-semibold text-slate-900">
            {{ sectionMode === 'server-rendered' ? 'Server-rendered' : 'Client-rendered' }}
          </p>
          <div class="space-y-1">
            <a
              v-for="item in NAV_ITEMS.filter((i) => i.mode === sectionMode)"
              :key="`${item.mode}:${item.transport}`"
              :href="toAppHref(item.href)"
              class="block rounded-lg px-3 py-2 text-sm transition"
              :class="item.mode === activeLocation.mode && item.transport === activeLocation.transport
                ? 'bg-white font-medium text-slate-900'
                : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'"
              @click.prevent="navigate(item.href)"
            >
              {{ item.title }}
            </a>
          </div>
        </div>
      </nav>
    </aside>

    <div class="space-y-6">
      <RestRoute
        v-if="activeLocation.transport === 'rest'"
        :key="`rest:${activeLocation.mode}`"
        :search="location.search"
        :presentation-mode="activeLocation.mode"
        @navigate="navigate"
      />
      <GraphqlRoute
        v-else
        :key="`graphql:${activeLocation.mode}`"
        :search="location.search"
        :presentation-mode="activeLocation.mode"
        @navigate="navigate"
      />

      <footer class="pt-2 text-center">
        <svg width="148" height="33" viewBox="0 0 148 33" role="img" aria-label="Verbb" class="mx-auto h-5 w-auto">
          <title>Verbb</title>
          <path d="M49.508.392c-8.65 0-15.328 6.724-17.34 12.974C28.904 23.498 35.4 32.32 45.194 32.32c6.057 0 11.377-2.498 14.52-5.642 1.332-1.33.486-2.157-.53-2.685-.558-.29-2.22-1.125-2.22-1.125-.9-.46-2.062-.523-3.046.045-1.405.807-2.765 2.148-7.704 2.148-3.972 0-6.907-2.673-7.443-6.308 0 0 16.407-.055 22.168-.055 1.93 0 2.62-1.572 2.62-4.48 0-8.3-6.138-13.825-14.052-13.825zM39.73 13.326c1.7-3.31 5.194-5.676 8.933-5.676 3.737 0 6.564 2.367 7.333 5.676H39.73zM32.706.953c1.236 0 1.86 1.055 1.295 2.265L20.623 29.532c-.68 1.34-2.08 2.228-3.506 2.228h-5.835c-1.236 0-2.23-.777-2.48-1.942L3.558 5.584H1.707c-.594 0-1.08-.358-1.233-.908L.01 2.994c-.27-.97.594-2.04 1.647-2.04h7.98c1.12 0 2.01.726 2.194 1.796l3.596 20.798L25.604 2.574c.472-.97 1.476-1.62 2.502-1.62h4.6zm107.615.03c4.638.333 7.803 4.197 7.133 8.968-.324 2.31-1.51 4.395-3.16 5.99 1.64 1.678 2.505 4.09 2.124 6.805-.71 5.056-5.387 9.09-10.44 9.09l-14.02-.04c-1.012-.003-1.716-.825-1.574-1.838l.026-.19c1.723-2.055 2.922-4.48 3.298-7.17.357-2.523-.07-4.977-1.183-7.053 1.172-1.77 1.94-3.735 2.22-5.74.3-2.137.03-4.156-.686-5.93l.14-1.01c.15-1.072 1.145-1.94 2.217-1.938l13.903.057zm-1.477 21.303c.256-1.82-.735-3.29-2.212-3.307l.003-.006h-7.025l-.932 6.627 7.025-.005c1.484-.015 2.887-1.487 3.143-3.31zm1.746-12.11c.262-1.884-.74-3.414-2.24-3.414h-7.026l-.96 6.827h7.024c1.502 0 2.936-1.53 3.2-3.414zM113.194.956c4.638.334 7.803 4.198 7.133 8.967-.324 2.31-1.51 4.395-3.16 5.992 1.64 1.676 2.504 4.09 2.124 6.803-.71 5.057-5.387 9.09-10.44 9.09l-14.02-.04c-1.012-.003-1.716-.825-1.574-1.838l3.818-27.093C97.226 1.767 98.214.9 99.284.9h.008l13.903.057zm-1.477 21.304c.256-1.82-.735-3.292-2.212-3.307l.002-.006h-7.025l-.932 6.627 7.026-.006c1.483-.015 2.886-1.486 3.142-3.308zm1.746-12.11c.263-1.885-.738-3.415-2.24-3.415H104.2l-.96 6.828h7.023c1.502 0 2.936-1.53 3.2-3.413zm-21.2-1.44c0 4.94-4.24 9.76-9.49 9.76l7 10.615c1.154 1.872.094 2.66-1.446 2.66l-4.3.01c-1.303 0-2.643-1.024-3.388-2.357l-5.424-10.504h-1.15L72.59 29.398c-.183 1.3-1.385 2.358-2.688 2.358h-3.266c-1.3 0-2.208-1.057-2.024-2.358L68.28 3.305c.18-1.3 1.385-2.358 2.686-2.358h13.66l-.005.017c4.87.087 7.645 3.852 7.645 7.745zm-8.226 1.368c.265-1.887-.737-3.415-2.24-3.415h-6.012l-.96 6.828h6.013c1.5 0 2.933-1.528 3.198-3.412z" fill="#e0e4ea" fill-rule="nonzero" />
        </svg>
      </footer>
    </div>
  </main>
</template>

// react/src/App.tsx
import { useEffect, useMemo, useState } from 'react';
import { FormieLogo, VerbbLogo } from './components/Branding';
import { GraphqlRoute } from './routes/GraphqlRoute';
import { RestRoute } from './routes/RestRoute';
import { stripAppBasePath, toAppHref } from './lib/routing';

type ModeId = 'server-rendered' | 'client-rendered';
type TransportId = 'rest' | 'graphql';
type BrowserLocationState = {
  pathname: string;
  search: string;
};

const NAV_ITEMS: Array<{
  mode: ModeId;
  transport: TransportId;
  title: string;
  href: string;
}> = [
    {
      mode: 'server-rendered',
      transport: 'rest',
      title: 'REST',
      href: '/server-rendered/rest?example=single-page&scenario=html-default-theme',
    },
    {
      mode: 'server-rendered',
      transport: 'graphql',
      title: 'GraphQL',
      href: '/server-rendered/graphql?example=single-page&demo=html-payload&scenario=html-default-theme',
    },
    {
      mode: 'client-rendered',
      transport: 'rest',
      title: 'REST',
      href: '/client-rendered/rest?example=single-page&scenario=component-rest-form',
    },
    {
      mode: 'client-rendered',
      transport: 'graphql',
      title: 'GraphQL',
      href: '/client-rendered/graphql?example=single-page&demo=component-payload',
    },
  ];

function readBrowserLocation(): BrowserLocationState {
  if (typeof window === 'undefined') {
    return {
      pathname: '/server-rendered/rest',
      search: '',
    };
  }

  return {
    pathname: stripAppBasePath(window.location.pathname || '/server-rendered/rest'),
    search: window.location.search,
  };
}

function normalizeLocation(pathname: string): { mode: ModeId; transport: TransportId } | null {
  const normalizedPathname = pathname === '/' ? '/server-rendered/rest' : pathname;
  const segments = normalizedPathname.split('/').filter(Boolean);

  if (segments.length < 2) {
    return null;
  }

  const [mode, transport] = segments;

  if ((mode === 'server-rendered' || mode === 'client-rendered') && (transport === 'rest' || transport === 'graphql')) {
    return {
      mode,
      transport,
    };
  }

  return null;
}

function App() {
  const [location, setLocation] = useState<BrowserLocationState>(() => {
    return readBrowserLocation();
  });

  useEffect(() => {
    const onPopState = () => {
      setLocation(readBrowserLocation());
    };

    window.addEventListener('popstate', onPopState);

    return () => {
      window.removeEventListener('popstate', onPopState);
    };
  }, []);

  const navigate = (url: string, options?: { replace?: boolean }) => {
    const method = options?.replace ? 'replaceState' : 'pushState';
    window.history[method]({}, '', toAppHref(url));
    setLocation(readBrowserLocation());
  };

  const activeLocation = useMemo(() => {
    return normalizeLocation(location.pathname) || { mode: 'server-rendered' as const, transport: 'rest' as const };
  }, [location.pathname]);

  useEffect(() => {
    if (normalizeLocation(location.pathname)) {
      return;
    }

    navigate(`/server-rendered/rest${location.search}`, { replace: true });
  }, [location.pathname, location.search]);

  return (
    <>
      <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/95 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-3 shadow-[0_8px_24px_-18px_rgba(15,23,42,0.35)] md:px-8">
          <a
            href={toAppHref('/server-rendered/rest?example=single-page&scenario=html-default-theme')}
            onClick={(event) => {
              event.preventDefault();
              navigate('/server-rendered/rest?example=single-page&scenario=html-default-theme');
            }}
            className="flex items-center gap-3"
          >
            <div className="size-6 shrink-0">
              <FormieLogo />
            </div>
            <div>
              <p className="text-lg font-semibold text-slate-900">Formie React Starter</p>
            </div>
          </a>
        </div>
      </header>

      <main className="mx-auto grid max-w-7xl gap-8 p-6 md:grid-cols-[14rem_minmax(0,1fr)] md:p-8">
        <aside className="md:sticky md:top-24 md:self-start">
          <nav className="space-y-6">
            {(['server-rendered', 'client-rendered'] as const).map((sectionMode) => {
              const sectionItems = NAV_ITEMS.filter((item) => {
                return item.mode === sectionMode;
              });

              return (
                <div key={sectionMode} className="space-y-2">
                  <p className="px-3 text-sm font-semibold text-slate-900">
                    {sectionMode === 'server-rendered' ? 'Server-rendered' : 'Client-rendered'}
                  </p>

                  <div className="space-y-1">
                    {sectionItems.map((item) => {
                      const isActive = item.mode === activeLocation.mode && item.transport === activeLocation.transport;

                      return (
                        <a
                          key={`${item.mode}:${item.transport}`}
                          href={toAppHref(item.href)}
                          onClick={(event) => {
                            event.preventDefault();
                            navigate(item.href);
                          }}
                          className={`block rounded-lg px-3 py-2 text-sm transition ${isActive
                            ? 'bg-white font-medium text-slate-900'
                            : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                            }`}
                        >
                          {item.title}
                        </a>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </nav>
        </aside>

        <div className="space-y-6">
          {activeLocation.transport === 'rest' ? (
            <RestRoute
              key={`${activeLocation.mode}:rest`}
              mode={activeLocation.mode}
              search={location.search}
              navigate={navigate}
              toAppHref={toAppHref}
            />
          ) : (
            <GraphqlRoute
              key={`${activeLocation.mode}:graphql`}
              mode={activeLocation.mode}
              search={location.search}
              navigate={navigate}
              toAppHref={toAppHref}
            />
          )}

          <footer className="pt-2 text-center">
            <VerbbLogo />
          </footer>
        </div>
      </main>
    </>
  );
}

export default App;
